language: java
sudo: false
jobs:
  include:
    - stage: build_test
      install: mvn clean install
    - stage: deploy
      script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
      before_install:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      install: mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true
      before_deploy:
        - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
        - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
          -v '\[')
      deploy:
        provider: releases
        api_key: ${env.GITHUB_TOKEN}
        file:
          - Mosaik-All/target/Mosaik-Framework.jar
          - IUI/target/IUI-$project_version.jar
          - AnnotationProcessing/target/AnnotationProcessing-$project_version.jar
          - Annotations/target/Annotations-$project_version.jar
          - ArgParser/target/ArgParser-$project_version.jar
          - ArgParser-Impl/target/ArgParser-Impl-$project_version.jar
          - Automatisation/target/Automatisation-$project_version.jar
          - Console/target/Console-$project_version.jar
          - Database/target/Database-$project_version.jar
          - DomParsing/target/DomParsing-$project_version.jar
          - DomParsing-Impl/target/DomParsing-Impl-$project_version.jar
          - Netty/target/Netty-$project_version.jar
          - Runtime/target/Runtime-$project_version.jar
          - Util/target/Util-$project_version.jar
          - ValueTransformer/target/ValueTransformer-$project_version.jar
          - WebApi/target/WebApi-$project_version.jar
          - Networking-Web/target/Networking-Web-$project_version.jar
        skip_cleanup: true
        name: $project_version
        on:
          repo: SplotyCode/Mosaik-Framework
          branch: master

after_success:
- bash <(curl -s https://codecov.io/bash)

stages:
  - name: build_test
  - name: deploy
    if: branch = master AND type != cron
